[package]
name = "rumblocks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
systemstat = "0.2.3"
tokio = { version = "1.0", features = ["full"] }
